<?php

/**
 * @file
 * Contains views_polygon_search.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_polygon_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_polygon_search module.
    case 'help.page.views_polygon_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}


